language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-6 build-essential libglm-dev libspdlog-dev libassimp-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
