language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-6 build-essential libspdlog-dev libassimp-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
script:
  - (wget https://github.com/g-truc/glm/releases/download/0.9.9.3/glm-0.9.9.3.zip && unzip -qq glm-0.9.9.3.zip && cd glm && mkdir build && cd build && cmake ../ && make && sudo make install)
  - mkdir build
  - cd build
  - cmake ../
  - make
